# Generated by Django 3.0.8 on 2020-08-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='till_date',
            field=models.DateField(),
        ),
    ]
