# Generated by Django 3.0.8 on 2020-08-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_auto_20200830_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=20),
        ),
    ]
