# Generated by Django 3.0.8 on 2020-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_auto_20200908_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='8763112592', max_length=30)),
                ('email', models.CharField(default='8763112592', max_length=40)),
                ('contact', models.CharField(default='8763112592', max_length=15)),
                ('message', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
