# Generated by Django 3.0.8 on 2020-09-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(default='Contact', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(default='Email', max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, default='Message...', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
