# Generated by Django 3.0.8 on 2020-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_auto_20200908_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.IntegerField(default='Contact', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(default='Email', max_length=40),
        ),
    ]
