# Generated by Django 3.0.8 on 2020-09-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0009_auto_20200908_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
