# Generated by Django 3.0.8 on 2020-09-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0014_auto_20200911_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
