# Generated by Django 3.0.8 on 2020-09-10 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_remove_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
