# Generated by Django 3.0.8 on 2020-09-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0017_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yt_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
