# Generated by Django 3.0.8 on 2020-09-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0018_project_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='neha', max_length=10)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
