# Generated by Django 3.0.8 on 2020-09-24 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0019_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='when',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
