# Generated by Django 3.0.8 on 2020-10-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0021_remove_pageview_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
